### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by aakhmerov** [zalora/myrapi#10]
Hi all, 

I am not a haskell developer, but I would like to give api wrapper a run to at least see list of parameters. And I got stuck during build process. 

Trying under Ubuntu, here is what I did: 

> cabal update
>  cabal install

I am always getting same error message 

> src/Myracloud/Types.hs:21:18:
>     Could not find module ‘Servant.Common.Text’
>     Perhaps you meant
>       Servant.Common.Req (from servant-client-0.8@serva_JQifRGzBlJd8gexEP3Zop8)
>     Use -v to see a list of the files searched for.
> cabal: Error: some packages failed to install:
> myrapi-0.1.0.0 failed during the building phase. The exception was:
> ExitFailure 1

any hint?

> ghc --version
> The Glorious Glasgow Haskell Compilation System, version 7.10.3

Thanks in agvance

**Comment by phunehehe** [comment]
@aakhmerov I haven't tried, but the [latest travis build](https://travis-ci.org/zalora/myrapi/builds/87195904) uses an older version of servant (0.4.4.5). You could try editing the cabal file to set that.

**Comment by aakhmerov** [comment]
hi @phunehehe,

thanks for quick reply. I get same error after changing to `servant >= 0.4.4.5`

> src/Myracloud/Types.hs:22:18:
>     Could not find module ‘Servant.Common.Text’
>     Perhaps you meant
>       Servant.Common.Req (from servant-client-0.8@serva_JQifRGzBlJd8gexEP3Zop8)
>     Use -v to see a list of the files searched for.
> cabal: Error: some packages failed to install:
> myrapi-0.1.0.0 failed during the building phase. The exception was:
> ExitFailure 1

**Comment by phunehehe** [comment]
@aakhmerov without an upper bound, `servant >= 0.4.4.5` would get you the latest version. I think you need `servant = 0.4.4.5`. Same for `servant-client`. Looks like this was [changed in servant 0.5](https://github.com/haskell-servant/servant/blob/8eb412ff23edf83baa7978587e71791fd9498b5a/servant/CHANGELOG.md#05).
