### ISSUE TITLE
Provide a mechanism to search for a DNS name

### ISSUE THREAD

**Issue by phunehehe** [zalora/myrapi#3]
This is needed to query the values associated with a certain name. The `list` command can be abused for this information (e.g `list` repeatedly until all pages are fetched, then filter from the result). It would be nicer, though, if the full list is provided via an option, or a `get` command is implemented.

**Comment by Fuuzetsu** [comment]
What kind of search options are you thinking about?

**Comment by phunehehe** [comment]
Search by subdomain name is what I thought about ("give me the json dump of
the record at abc.zalora.com, if any"). I'm not sure if that's
easier/better than "give me all records under zalora.com" though.

**Comment by Fuuzetsu** [comment]
Myra doesn't provide such a thing so it's not easier in that aspect. At best we can implement it ourselves. The question is indeed whether we just print all records from every page or filter by subdomain too.

**Comment by phunehehe** [comment]
Just printing everything will be enough for me 😃

**Comment by Fuuzetsu** [comment]
Oops, didn't see your message on time. Oh well. You can now search for subdomains with the `search` command. You can list every record for a domain without filtering by using `list` without `--page` argument.
